# Generated by Django 4.1.6 on 2023-02-10 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('MU', 'Music'), ('VI', 'Video'), ('SH', 'Show'), ('ME', 'Merchandise'), ('SO', 'Social Media'), ('NE', 'News')], max_length=2)),
                ('user_review', models.CharField(blank=True, max_length=500, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('music_type', models.CharField(choices=[('AL', 'ALBUM'), ('SI', 'Single'), ('MI', 'Mixtape'), ('EP', 'EP'), ('FE', 'Features On')], max_length=2)),
                ('show_venue_name', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
