# Generated by Django 4.1.6 on 2023-02-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_experience_music_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='music_type',
            field=models.CharField(blank=True, choices=[('AL', 'Album'), ('SI', 'Single'), ('MI', 'Mixtape'), ('EP', 'EP'), ('FE', 'Features On')], max_length=2, null=True),
        ),
    ]
