# Generated by Django 4.1.6 on 2023-02-15 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_comment_experience_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='artist',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='main_app.artist'),
            preserve_default=False,
        ),
    ]
