# Generated by Django 4.1.6 on 2023-02-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
