# Generated by Django 4.1.6 on 2023-02-16 00:50

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_artist_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
