# Generated by Django 4.1.6 on 2023-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='video',
            new_name='profile_photo',
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('MU', 'Music'), ('SH', 'Show'), ('ME', 'Merchandise'), ('SO', 'Social Media'), ('NE', 'News')], max_length=2),
        ),
    ]
